# Generated by Django 4.2.2 on 2023-07-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodegas.region'),
        ),
    ]
