# Generated by Django 4.2.2 on 2023-07-19 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodegas', '0003_bodegaproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodegaproducto',
            name='bodega',
        ),
        migrations.AddField(
            model_name='bodegaproducto',
            name='bodegaDestino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodega_destino', to='bodegas.bodega', verbose_name='Bodega de destino'),
        ),
        migrations.AddField(
            model_name='bodegaproducto',
            name='bodegaOrigen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodega_origen', to='bodegas.bodega', verbose_name='Bodega de origen'),
        ),
        migrations.AddField(
            model_name='bodegaproducto',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='movimiento_por',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='bodegas.bodega', verbose_name='Bodega de destino')),
                ('bodega_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='bodegas.bodega', verbose_name='Bodega de origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
