# Generated by Django 4.2.2 on 2023-07-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0004_remove_bodegaproducto_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento_por',
            name='bodega_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='bodegas.bodega', verbose_name='Bodega de destino'),
        ),
        migrations.AlterField(
            model_name='movimiento_por',
            name='bodega_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='bodegas.bodega', verbose_name='Bodega de origen'),
        ),
    ]
