# Generated by Django 4.2.2 on 2023-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_usuario_id_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
